import { z } from "zod";

export const createStudentSchema = z.object({
  body: z.object({
    branchId: z.string().min(1, "branchId is required"),
    classId: z.string().min(1, "classId is required"),
    sectionId: z.string().min(1, "sectionId is required"),
    name: z.string().min(1, "Student name is required"),
    email: z.string().email("Valid email required"),
    phone: z.string().optional(),
    dateOfBirth: z.coerce.date({ errorMap: () => ({ message: "Valid dateOfBirth is required" }) }),
    gender: z.enum(["MALE", "FEMALE", "OTHER"]),
    bloodGroup: z.string().optional(),
    religion: z.string().optional(),
    caste: z.string().optional(),
    category: z.string().optional(),
    nationality: z.string().optional(),
    motherTongue: z.string().optional(),
    address: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    pincode: z.string().optional(),
    previousSchool: z.string().optional(),
    cardId: z.string().optional(),
    fatherName: z.string().optional(),
    fatherEmail: z.string().email("Valid father email required").optional().or(z.literal("")),
    fatherPhone: z.string().optional(),
    fatherOccupation: z.string().optional(),
    motherName: z.string().optional(),
    motherEmail: z.string().email("Valid mother email required").optional().or(z.literal("")),
    motherPhone: z.string().optional(),
    motherOccupation: z.string().optional(),
  }),
});

export const updateStudentSchema = z.object({
  body: z.object({
    classId: z.string().optional(),
    sectionId: z.string().optional(),
    rollNo: z.string().optional(),
    dateOfBirth: z.coerce.date().optional(),
    gender: z.enum(["MALE", "FEMALE", "OTHER"]).optional(),
    bloodGroup: z.string().optional(),
    religion: z.string().optional(),
    caste: z.string().optional(),
    category: z.string().optional(),
    nationality: z.string().optional(),
    motherTongue: z.string().optional(),
    address: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    pincode: z.string().optional(),
    cardId: z.string().optional(),
    name: z.string().optional(),
    phone: z.string().optional(),
    isActive: z.boolean().optional(),
  }),
});
